### ISSUE TITLE
.filter() listed twice in Observable's methods. 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon-docs#109]
![screenshot 2016-08-15 15 07 59](https://cloud.githubusercontent.com/assets/863286/17681365/27400fa8-62fa-11e6-9565-493a3b1d5b82.png)

Also the list should probably be alphabetized.

**Comment by deontologician** [comment]
Actually, we should probably remove the individual links in favor of a direct link to the Observable documentation. Now we include all methods, so listing which ones we use doesn't make as much sense
