### ISSUE TITLE
Link to RxJS when we talk about Observables

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon-docs#15]
We should link to the corresponding sections of http://rxjs.codeplex.com/wikipage?title=Observable&referringTitle=Documentation in a few places of our documentation. For example we currently have a description of the `forEach` method in https://github.com/rethinkdb/horizon-docs/blob/master/api/collection.md#collectionforeach-foreach , but don't point out that this is the standard `Observable` `forEach`.

**Comment by chipotle** [comment]
The `Collection` documentation links to RxJS now, both when talking about `fetch` and `subscribe` (and we no longer talk about `forEach` directly).
