### ISSUE TITLE
Multi-line ES6 template string not highlighting correctly

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon-docs#30]
<img width="631" alt="screenshot 2016-05-15 15 35 37" src="https://cloud.githubusercontent.com/assets/863286/15276615/bc382568-1ab2-11e6-84fa-b3259862342a.png">

http://localhost:4000/docs-archive/readme

**Comment by chipotle** [comment]
This isn't a bug we can address here, since it's in the Jekyll syntax highlighter. Either the highlighter is going to have to be smarter or we're going to have to override its CSS (which isn't a job for the docs repository).
