### ISSUE TITLE
Getting started document doesn't give enough structure

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon-docs#49]
Opened by @danielcompton in https://github.com/rethinkdb/horizon/issues/402 : 

--

The [getting started](http://horizon.io/docs/getting-started/) document has a lot of good information, but doesn't tie all of the information together into an application. For example:

* In the "putting it all together" section, it doesn't say where the JS file should be saved.
* `renderChats` is mentioned once in the getting started document, but never defined AFAICT.
* There is no updated HTML page to render the chat messages into.

Lots of good stuff there, but not quite enough to get a working application on my part without expending more brain energy to fill in the gaps.

**Comment by danielmewes** [comment]
Useful feedback @danielcompton. I think the intention was to leave the rendering part to the example applications. We should make the connection clearer and also add the other missing pieces you mention.

**Comment by danielcompton** [comment]
I wonder if a simple JQuery implementation similar to Socket.io's [chat application example](http://socket.io/get-started/chat/) would be a good starting point here before digging into the deeper example applications just to finish off what's shown there?

**Comment by chipotle** [comment]
@dalanmiller -- I've made you a co-assignee because the "Putting it all together" code is mostly yours, and you'll probably have better ideas on where to go with this.

**Comment by chipotle** [comment]
Pinging @dalanmiller again. :) I think you could probably turn the "Putting it all together" code into an actual quick application, although if there's one that already exists in examples that could be put in there, I could edit it in.

**Comment by dalanmiller** [comment]
I've been summoned! ✨ 🔮 ✨  (apologies for missing the first notification, the Github deluge is strong)

Rather than a giant text blog in the actual document would it help if the final version were in it's own repo?

**Comment by chipotle** [comment]
Maybe, but I feel like we need to have _something_ in the actual document that goes in the "Putting it all together" section beyond a link to Github. :)
