### ISSUE TITLE
fetch docs probably shouldn't mention forEach

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon-docs#56]
Technically, you can call forEach on fetch, but it's not very useful since there will only ever be a single item (an array, or in the case of a `.find` query, an object). We should probably just remove mention of forEach from fetch. It's more useful for `.watch` where you'll actually get multiple items on the observable

**Comment by hnordt** [comment]
Another problem I see with forEach is that you can't unsubscribe as discussed in https://github.com/rethinkdb/horizon/issues/457
