### ISSUE TITLE
horizon client getting started guide

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon-docs#57]
Migrated from rethinkdb/horizon#433 by @hnordt 

In http://horizon.io/docs/getting-started/ the docs say:

> However, if you’re using [Webpack][] or a similar build setup, or requesting the .js library at load time isn’t desirable, just add the client library as an NPM dependency (npm install @horizon/client).
>
> In your application, you’ll need to include the Horizon client file, and specify the Horizon port number when initializing the connection.

```js
<script src="localhost:8181/horizon/horizon.js"></script>

// Specify the host property for initializing the Horizon connection
const horizon = Horizon({host: 'localhost:8181'});
```

`In your application, you’ll need to include the Horizon client file, and specify the Horizon port number when initializing the connection.` shouldn't be `In your application, you’ll need to import the Horizon client file, and specify the Horizon port number when initializing the connection.`?

Also the code shouldn't be:

```js
import Horizon from '@horizon/client';

// Specify the host property for initializing the Horizon connection
const horizon = Horizon({host: 'localhost:8181'});
```

?

**Comment by chipotle** [comment]
I think it might be better to reword this just a bit so we have two examples, one with Webpack and one without.

**Comment by saidimu** [comment]
@chipotle At this point there is basically no straight-forward way to import `@horizon/client` from Node. Between this issue, rethinkdb/horizon#185, rethinkdb/horizon#263, rethinkdb/horizon#420 and possibly many more, it seems Node.js isn't a common enough use-case (or not part of the design considerations)?

**Comment by danielmewes** [comment]
@saidimu This functionality fell under the cracks for the initial Horizon 1.0.0 release, but we definitely want to make this possible (and easy) asap. The next version shouldn't take too long.
