### ISSUE TITLE
Incorrect mention of user/password in authentication docs

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon-docs#72]
In the short summary at the top of the documentation for authentication, for Anonymous auth the sentence "Your application will need to prompt for username and password." is incorrect.

That sentence should probably just be removed, it's correct otherwise.

**Comment by tslocke** [comment]
On the same docs page, a little further down under the "Using local authentication" heading, it also says 

> This is essentially the means of “Creating an account” or “Signing up” for people who use your website.

which lead me to believe this was a way to implement typical username+password auth. With a little further reading that appears not to be the case, as the "account" is forever constrained to the browser first used.

Would suggest taking this out too.

**Comment by chipotle** [comment]
Okay, I think maybe I should get a "use case" summary from the developers explaining when someone would want to use anonymous authentication and when someone would want to use local authentication. I thought I'd understood this from previous conversations, but clearly I did not.

**Comment by chipotle** [comment]
Pinging @deontologician and @dalanmiller re: the use case summary.

**Comment by deontologician** [comment]
This is for creating a user just for a particular browser. I don't know that there's a particular use case, but it's inaccurate to say you should combine it with password auth, since you can't do that. @Tryneus might have a use case in mind (maybe)
