### ISSUE TITLE
Incorrect `auto_create_table` option in "Configuring Horizon"

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/horizon-docs#75]
As seen in rethinkdb/horizon#442, the `auto_create_table` option is actually `auto_create_collection`.

This should be updated in [Configuring Horizon](http://horizon.io/docs/configuration/). We should verify other [Horizon server options](https://github.com/rethinkdb/horizon/blob/061f784fa6f8cd6b30ffcaf6b88e823e0e386b3f/server/src/schema/server_options.js).

**Comment by danielmewes** [comment]
I just opened a PR for this https://github.com/rethinkdb/horizon-docs/pull/76

I believe the other options are up-to-date.

**Comment by chipotle** [comment]
Fixed in the now-merged #76
