### ISSUE TITLE
Added .take to Observable methods

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon-docs#80]
This came in in the most recent version http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-take

**Comment by danielmewes** [comment]
Where in the docs would this go? Do we even have a list of Observable methods at the moment?

**Comment by deontologician** [comment]
We do, but I forget where. @chipotle added a section recently

**Comment by chipotle** [comment]
As in this afternoon. It isn't deployed yet, but it'll be up tomorrow (and we can add in this ticket).
