### ISSUE TITLE
Basic Docker setup

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/horizon-docs#83]
We should have an article on using Horizon in a basic Docker setup (@dalanmiller is working on this). Ideally we'd include details on using LetsEncrypt for a basic, production-ready setup with SSL / TLS.

@dalanmiller: could you include an outline and details that should be covered?

**Comment by dalanmiller** [comment]
Got a start to this in pull #86

**Comment by chipotle** [comment]
This was merged in #86.
