### ISSUE TITLE
Schema clarity

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon-docs#89]
- [x] We should specify a place for a schema.toml file to live, I vote `.hz/schema.toml` - http://horizon.io/docs/permissions/
- [x] we should be explicit that the schema declarations do not go inside `.hz/config.toml` (I made this mistake, and don't think it would be unreasonable for others to assume the same) 
- [ ] We should have an example showing how to move an application from local to a production environment which involves a schema migration .
 - For the mean time this will have to be without [being able to specify `schema.toml` to `hz serve`](https://github.com/rethinkdb/horizon/issues/548#issuecomment-228497130)

**Comment by chipotle** [comment]
I'm pretty sure that the first two of these are already taken care of (at least in Horizon 2.0). I don't know about the third one, since in 2.0 you *can* specify a schema file with `hz serve`.

**Comment by dalanmiller** [comment]
@chipotle I'm going to close this and open a new issue...
