### ISSUE TITLE
Documentation should probably use camelCase in code examples

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon-docs#91]
I was reading the docs on http://horizon.io/docs/embed/ and it uses underscores in variable names for the JS examples.

**Comment by chipotle** [comment]
Does the Horizon object accept option keys in camelCase, or just snake_case as shown here? (For that matter, are the instance methods camelCase or snake_case? AFAICT it's `add_auth_provider()`, not `addAuthProvider()`.)

**Comment by mlucy** [comment]
Right now the options have to be snake_case (I opened https://github.com/rethinkdb/horizon/issues/620 to complain about that).  I could see an argument for leaving the variable names in snake_case until the API changes so that the examples aren't mixing styles, if you think that would be better.
