### ISSUE TITLE
Instructions for configuring OAuth providers is unclear

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon-docs#92]
Chris and I spent about 15 minutes trying to figure out what `horizon_instance.auth.github` meant.  `horizon_instance` isn't used anywhere else on the page.  The example at the top of the page that `require`s things calls that variable `horizon`; we should give it a consistent name in both places.

**Comment by mlucy** [comment]
(Er, on the page http://horizon.io/docs/embed/ .)

**Comment by chipotle** [comment]
I'll fix this as part of #90. (The original examples I got for the page all used `horizon_instance`, IIRC. I changed them to `horizon` but missed this one.)
