### ISSUE TITLE
Docs tell people to write `require('horizon')` instead of to load `horizon/horizon.js`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon-docs#93]
The docs for how to connect to a Horizon server (e.g. on http://horizon.io/api/collection/) tell people to write `const Horizon = require("horizon")`.  This has a few problems:
* It only works if people are using a build system like browserify.
* Our examples don't appear to do it this way.
* @Tryneus mentioned to me a month or two ago that he doesn't recommend people do it, because it prevents the server from serving a version of the Horizon client that it knows it's compatible with.
* It breaks Horizon Cloud (at least at the moment).

The docs should probably instead tell people that they need to put `<script src="/horizon/horizon.js"></script>` somewhere above where they use `Horizon`.

**Comment by chipotle** [comment]
In this context -- the JS code -- shouldn't it just become:

```js
const Horizon = new Horizon();
```

This matches the (brand new) Getting Started example. The `<script>` tag probably doesn't belong in the API docs; by the time you get there, Horizon is already loaded, one way or another.

**Comment by mlucy** [comment]
Cool, that sounds good then.

**Comment by mlucy** [comment]
(Although it should probably be `const hz = Horizon()` instead of `const Horizon = Horizon()`, at least the way the page is written now.)
